const bcrypt = require("bcryptjs");

const users = [
  {
    name: "Antony Kumar",
    email: "antonykumar27@gmail.com",
    gender: "Male",
    password: "123456",
    role: "User",
  },
  {
    name: "Aarav Sharma",
    email: "aarav.sharma@gmail.com",
    gender: "Male",
    password: "123456",
    role: "User",
  },
  {
    name: "Diya Nair",
    email: "diya.nair@gmail.com",
    gender: "Female",
    password: "123456",
    role: "User",
  },
  {
    name: "Rohan Mehta",
    email: "rohan.mehta@gmail.com",
    gender: "Male",
    password: "123456",
    role: "User",
  },
  {
    name: "Sneha Iyer",
    email: "sneha.iyer@gmail.com",
    gender: "Female",
    password: "123456",
    role: "User",
  },
  {
    name: "Vivaan Reddy",
    email: "vivaan.reddy@gmail.com",
    gender: "Male",
    password: "123456",
    role: "User",
  },
  {
    name: "Ananya Menon",
    email: "ananya.menon@gmail.com",
    gender: "Female",
    password: "123456",
    role: "User",
  },
  {
    name: "Krishna Patel",
    email: "krishna.patel@gmail.com",
    gender: "Male",
    password: "123456",
    role: "User",
  },
  {
    name: "Meera Das",
    email: "meera.das@gmail.com",
    gender: "Female",
    password: "123456",
    role: "User",
  },
  {
    name: "Arjun Varma",
    email: "arjun.varma@gmail.com",
    gender: "Male",
    password: "123456",
    role: "User",
  },
  {
    name: "Pooja Pillai",
    email: "pooja.pillai@gmail.com",
    gender: "Female",
    password: "123456",
    role: "User",
  },
  {
    name: "Karan Rao",
    email: "karan.rao@gmail.com",
    gender: "Male",
    password: "123456",
    role: "User",
  },
  {
    name: "Ishita Rani",
    email: "ishita.rani@gmail.com",
    gender: "Female",
    password: "123456",
    role: "User",
  },
  {
    name: "Nikhil Joshi",
    email: "nikhil.joshi@gmail.com",
    gender: "Male",
    password: "123456",
    role: "User",
  },
  {
    name: "Lavanya Jain",
    email: "lavanya.jain@gmail.com",
    gender: "Female",
    password: "123456",
    role: "User",
  },
  {
    name: "Siddharth Bhat",
    email: "siddharth.bhat@gmail.com",
    gender: "Male",
    password: "123456",
    role: "User",
  },
  {
    name: "Aishwarya Sen",
    email: "aishwarya.sen@gmail.com",
    gender: "Female",
    password: "123456",
    role: "User",
  },
  {
    name: "Ritik Kumar",
    email: "ritik.kumar@gmail.com",
    gender: "Male",
    password: "123456",
    role: "User",
  },
  {
    name: "Priya Kaul",
    email: "priya.kaul@gmail.com",
    gender: "Female",
    password: "123456",
    role: "User",
  },
  {
    name: "Aman Mishra",
    email: "aman.mishra@gmail.com",
    gender: "Male",
    password: "123456",
    role: "User",
  },
  {
    name: "Tanya George",
    email: "tanya.george@gmail.com",
    gender: "Female",
    password: "123456",
    role: "User",
  },
  {
    name: "Yash Thakur",
    email: "yash.thakur@gmail.com",
    gender: "Male",
    password: "123456",
    role: "User",
  },
  {
    name: "Neha Balan",
    email: "neha.balan@gmail.com",
    gender: "Female",
    password: "123456",
    role: "User",
  },
  {
    name: "Dev Malhotra",
    email: "dev.malhotra@gmail.com",
    gender: "Male",
    password: "123456",
    role: "User",
  },
  {
    name: "Kritika D'Souza",
    email: "kritika.dsouza@gmail.com",
    gender: "Female",
    password: "123456",
    role: "User",
  },
  {
    name: "Harsh Kapoor",
    email: "harsh.kapoor@gmail.com",
    gender: "Male",
    password: "123456",
    role: "User",
  },
  {
    name: "Riya Joseph",
    email: "riya.joseph@gmail.com",
    gender: "Female",
    password: "123456",
    role: "User",
  },
  {
    name: "Rahul Deshmukh",
    email: "rahul.deshmukh@gmail.com",
    gender: "Male",
    password: "123456",
    role: "User",
  },
  {
    name: "Shreya Fernandes",
    email: "shreya.fernandes@gmail.com",
    gender: "Female",
    password: "123456",
    role: "User",
  },
  {
    name: "Mohit Sinha",
    email: "mohit.sinha@gmail.com",
    gender: "Male",
    password: "123456",
    role: "User",
  },
  {
    name: "Divya John",
    email: "divya.john@gmail.com",
    gender: "Female",
    password: "123456",
    role: "User",
  },
  {
    name: "Saurav Yadav",
    email: "saurav.yadav@gmail.com",
    gender: "Male",
    password: "123456",
    role: "User",
  },
  {
    name: "Nivedita Antony",
    email: "nivedita.antony@gmail.com",
    gender: "Female",
    password: "123456",
    role: "User",
  },
  {
    name: "Tarun Sengupta",
    email: "tarun.sengupta@gmail.com",
    gender: "Male",
    password: "123456",
    role: "User",
  },
  {
    name: "Aparna Mathew",
    email: "aparna.mathew@gmail.com",
    gender: "Female",
    password: "123456",
    role: "User",
  },
  {
    name: "Vikas Chatterjee",
    email: "vikas.chatterjee@gmail.com",
    gender: "Male",
    password: "123456",
    role: "User",
  },
  {
    name: "Simran Roy",
    email: "simran.roy@gmail.com",
    gender: "Female",
    password: "123456",
    role: "User",
  },
  {
    name: "Abhishek Paul",
    email: "abhishek.paul@gmail.com",
    gender: "Male",
    password: "123456",
    role: "User",
  },
  {
    name: "Radhika Dey",
    email: "radhika.dey@gmail.com",
    gender: "Female",
    password: "123456",
    role: "User",
  },
  {
    name: "Gaurav Khan",
    email: "gaurav.khan@gmail.com",
    gender: "Male",
    password: "123456",
    role: "User",
  },
  {
    name: "Bhavana Jacob",
    email: "bhavana.jacob@gmail.com",
    gender: "Female",
    password: "123456",
    role: "User",
  },
  {
    name: "Naveen Saxena",
    email: "naveen.saxena@gmail.com",
    gender: "Male",
    password: "123456",
    role: "User",
  },
  {
    name: "Devika Nambiar",
    email: "devika.nambiar@gmail.com",
    gender: "Female",
    password: "123456",
    role: "User",
  },
  {
    name: "Rajeev Naik",
    email: "rajeev.naik@gmail.com",
    gender: "Male",
    password: "123456",
    role: "User",
  },
  {
    name: "Shruti Zachariah",
    email: "shruti.zachariah@gmail.com",
    gender: "Female",
    password: "123456",
    role: "User",
  },
  {
    name: "Ankit Rane",
    email: "ankit.rane@gmail.com",
    gender: "Male",
    password: "123456",
    role: "User",
  },
  {
    name: "Jasmine Kurien",
    email: "jasmine.kurien@gmail.com",
    gender: "Female",
    password: "123456",
    role: "User",
  },
  {
    name: "Pranav Pillai",
    email: "pranav.pillai@gmail.com",
    gender: "Male",
    password: "123456",
    role: "User",
  },
  {
    name: "Sanya Rehman",
    email: "sanya.rehman@gmail.com",
    gender: "Female",
    password: "123456",
    role: "User",
  },
  {
    name: "Manoj Kumar",
    email: "manoj.kumar@gmail.com",
    gender: "Male",
    password: "123456",
    role: "User",
  },
  {
    name: "Kavya Rajan",
    email: "kavya.rajan@gmail.com",
    gender: "Female",
    password: "123456",
    role: "User",
  },
  {
    name: "Suresh Nair",
    email: "suresh.nair@gmail.com",
    gender: "Male",
    password: "123456",
    role: "User",
  },
  {
    name: "Anjali Prasad",
    email: "anjali.prasad@gmail.com",
    gender: "Female",
    password: "123456",
    role: "User",
  },
  {
    name: "Pradeep Singh",
    email: "pradeep.singh@gmail.com",
    gender: "Male",
    password: "123456",
    role: "User",
  },
  {
    name: "Ritika Sharma",
    email: "ritika.sharma@gmail.com",
    gender: "Female",
    password: "123456",
    role: "User",
  },
  {
    name: "Vinod Das",
    email: "vinod.das@gmail.com",
    gender: "Male",
    password: "123456",
    role: "User",
  },
  {
    name: "Chitra Antony",
    email: "chitra.antony@gmail.com",
    gender: "Female",
    password: "123456",
    role: "User",
  },
  {
    name: "Akhil Sinha",
    email: "akhil.sinha@gmail.com",
    gender: "Male",
    password: "123456",
    role: "User",
  },
  {
    name: "Deepika Rani",
    email: "deepika.rani@gmail.com",
    gender: "Female",
    password: "123456",
    role: "User",
  },
  {
    name: "Rahul Nambiar",
    email: "rahul.nambiar@gmail.com",
    gender: "Male",
    password: "123456",
    role: "User",
  },
  {
    name: "Jyoti Kumari",
    email: "jyoti.kumari@gmail.com",
    gender: "Female",
    password: "123456",
    role: "User",
  },
  {
    name: "Farhan Khan",
    email: "farhan.khan@gmail.com",
    gender: "Male",
    password: "123456",
    role: "User",
  },
  {
    name: "Sujatha Iyer",
    email: "sujatha.iyer@gmail.com",
    gender: "Female",
    password: "123456",
    role: "User",
  },
  {
    name: "Sameer Verma",
    email: "sameer.verma@gmail.com",
    gender: "Male",
    password: "123456",
    role: "User",
  },
  {
    name: "Neelam Thomas",
    email: "neelam.thomas@gmail.com",
    gender: "Female",
    password: "123456",
    role: "User",
  },
  {
    name: "Uday Menon",
    email: "uday.menon@gmail.com",
    gender: "Male",
    password: "123456",
    role: "User",
  },
  {
    name: "Reshma Kaur",
    email: "reshma.kaur@gmail.com",
    gender: "Female",
    password: "123456",
    role: "User",
  },
  {
    name: "Alok Bhat",
    email: "alok.bhat@gmail.com",
    gender: "Male",
    password: "123456",
    role: "User",
  },
  {
    name: "Snehal Roy",
    email: "snehal.roy@gmail.com",
    gender: "Female",
    password: "123456",
    role: "User",
  },
  {
    name: "Vishal Pandey",
    email: "vishal.pandey@gmail.com",
    gender: "Male",
    password: "123456",
    role: "User",
  },
  {
    name: "Roshni David",
    email: "roshni.david@gmail.com",
    gender: "Female",
    password: "123456",
    role: "User",
  },
  {
    name: "Nitin Joshi",
    email: "nitin.joshi@gmail.com",
    gender: "Male",
    password: "123456",
    role: "User",
  },
  {
    name: "Namrata Fernandes",
    email: "namrata.fernandes@gmail.com",
    gender: "Female",
    password: "123456",
    role: "User",
  },
  {
    name: "Ashok Reddy",
    email: "ashok.reddy@gmail.com",
    gender: "Male",
    password: "123456",
    role: "User",
  },
  {
    name: "Leela John",
    email: "leela.john@gmail.com",
    gender: "Female",
    password: "123456",
    role: "User",
  },
  {
    name: "Girish Pawar",
    email: "girish.pawar@gmail.com",
    gender: "Male",
    password: "123456",
    role: "User",
  },
  {
    name: "Swati Saxena",
    email: "swati.saxena@gmail.com",
    gender: "Female",
    password: "123456",
    role: "User",
  },
  {
    name: "Ramesh Pillai",
    email: "ramesh.pillai@gmail.com",
    gender: "Male",
    password: "123456",
    role: "User",
  },
  {
    name: "Vani George",
    email: "vani.george@gmail.com",
    gender: "Female",
    password: "123456",
    role: "User",
  },
  {
    name: "Ajay Kulkarni",
    email: "ajay.kulkarni@gmail.com",
    gender: "Male",
    password: "123456",
    role: "User",
  },
  {
    name: "Haripriya Rao",
    email: "haripriya.rao@gmail.com",
    gender: "Female",
    password: "123456",
    role: "User",
  },
  {
    name: "Arvind Mathur",
    email: "arvind.mathur@gmail.com",
    gender: "Male",
    password: "123456",
    role: "User",
  },
  {
    name: "Sowmya Cherian",
    email: "sowmya.cherian@gmail.com",
    gender: "Female",
    password: "123456",
    role: "User",
  },
  {
    name: "Raghu Patil",
    email: "raghu.patil@gmail.com",
    gender: "Male",
    password: "123456",
    role: "User",
  },
  {
    name: "Ayesha Dey",
    email: "ayesha.dey@gmail.com",
    gender: "Female",
    password: "123456",
    role: "User",
  },
  {
    name: "Narayan Mohan",
    email: "narayan.mohan@gmail.com",
    gender: "Male",
    password: "123456",
    role: "User",
  },
  {
    name: "Keerthi Zachariah",
    email: "keerthi.zachariah@gmail.com",
    gender: "Female",
    password: "123456",
    role: "User",
  },
  {
    name: "Sanket Paul",
    email: "sanket.paul@gmail.com",
    gender: "Male",
    password: "123456",
    role: "User",
  },
  {
    name: "Trisha Nair",
    email: "trisha.nair@gmail.com",
    gender: "Female",
    password: "123456",
    role: "User",
  },
  {
    name: "Ravi Naidu",
    email: "ravi.naidu@gmail.com",
    gender: "Male",
    password: "123456",
    role: "User",
  },
  {
    name: "Vaishnavi Menon",
    email: "vaishnavi.menon@gmail.com",
    gender: "Female",
    password: "123456",
    role: "User",
  },
  {
    name: "Imran Sheikh",
    email: "imran.sheikh@gmail.com",
    gender: "Male",
    password: "123456",
    role: "User",
  },
  {
    name: "Aparajita Singh",
    email: "aparajita.singh@gmail.com",
    gender: "Female",
    password: "123456",
    role: "User",
  },
  {
    name: "Sanjay Patra",
    email: "sanjay.patra@gmail.com",
    gender: "Male",
    password: "123456",
    role: "User",
  },
  {
    name: "Ira Joseph",
    email: "ira.joseph@gmail.com",
    gender: "Female",
    password: "123456",
    role: "User",
  },
  {
    name: "Anshul Kaushik",
    email: "anshul.kaushik@gmail.com",
    gender: "Male",
    password: "123456",
    role: "User",
  },
  {
    name: "Rekha Dsouza",
    email: "rekha.dsouza@gmail.com",
    gender: "Female",
    password: "123456",
    role: "User",
  },
  {
    name: "Kiran Bedi",
    email: "kiran.bedi@gmail.com",
    gender: "Female",
    password: "123456",
    role: "User",
  },
  {
    name: "Avinash Gokhale",
    email: "avinash.gokhale@gmail.com",
    gender: "Male",
    password: "123456",
    role: "User",
  },
  {
    name: "Deepa Narayan",
    email: "deepa.narayan@gmail.com",
    gender: "Female",
    password: "123456",
    role: "User",
  },
  {
    name: "Rishabh Pant",
    email: "rishabh.pant@gmail.com",
    gender: "Male",
    password: "123456",
    role: "User",
  },
  {
    name: "Urvashi Rautela",
    email: "urvashi.rautela@gmail.com",
    gender: "Female",
    password: "123456",
    role: "User",
  },
  {
    name: "Naveen Jindal",
    email: "naveen.jindal@gmail.com",
    gender: "Male",
    password: "123456",
    role: "User",
  },
  {
    name: "Charu Sharma",
    email: "charu.sharma@gmail.com",
    gender: "Female",
    password: "123456",
    role: "User",
  },
  {
    name: "Manoj Tiwari",
    email: "manoj.tiwari@gmail.com",
    gender: "Male",
    password: "123456",
    role: "User",
  },
  {
    name: "Jhanvi Kapoor",
    email: "jhanvi.kapoor@gmail.com",
    gender: "Female",
    password: "123456",
    role: "User",
  },
  {
    name: "Ashwin Kumar",
    email: "ashwin.kumar@gmail.com",
    gender: "Male",
    password: "123456",
    role: "User",
  },
  {
    name: "Radhika Apte",
    email: "radhika.apte@gmail.com",
    gender: "Female",
    password: "123456",
    role: "User",
  },
  {
    name: "Bharat Bhushan",
    email: "bharat.bhushan@gmail.com",
    gender: "Male",
    password: "123456",
    role: "User",
  },
  {
    name: "Smita Irani",
    email: "smita.irani@gmail.com",
    gender: "Female",
    password: "123456",
    role: "User",
  },
  {
    name: "Dheeraj Dhoopar",
    email: "dheeraj.dhoopar@gmail.com",
    gender: "Male",
    password: "123456",
    role: "User",
  },
  {
    name: "Kriti Sanon",
    email: "kriti.sanon@gmail.com",
    gender: "Female",
    password: "123456",
    role: "User",
  },
  {
    name: "Eshan Sharma",
    email: "eshan.sharma@gmail.com",
    gender: "Male",
    password: "123456",
    role: "User",
  },
  {
    name: "Dia Mirza",
    email: "dia.mirza@gmail.com",
    gender: "Female",
    password: "123456",
    role: "User",
  },
  {
    name: "Farhan Akhtar",
    email: "farhan.akhtar@gmail.com",
    gender: "Male",
    password: "123456",
    role: "User",
  },
  {
    name: "Zoya Khan",
    email: "zoya.khan@gmail.com",
    gender: "Female",
    password: "123456",
    role: "User",
  },
  {
    name: "Ishaan Khattar",
    email: "ishaan.khattar@gmail.com",
    gender: "Male",
    password: "123456",
    role: "User",
  },
  {
    name: "Tara Sutaria",
    email: "tara.sutaria@gmail.com",
    gender: "Female",
    password: "123456",
    role: "User",
  },
  {
    name: "Kabir Bedi",
    email: "kabir.bedi@gmail.com",
    gender: "Male",
    password: "123456",
    role: "User",
  },
  {
    name: "Nimrat Kaur",
    email: "nimrat.kaur@gmail.com",
    gender: "Female",
    password: "123456",
    role: "User",
  },
  {
    name: "Ranveer Brar",
    email: "ranveer.brar@gmail.com",
    gender: "Male",
    password: "123456",
    role: "User",
  },
  {
    name: "Malaika Arora",
    email: "malaika.arora@gmail.com",
    gender: "Female",
    password: "123456",
    role: "User",
  },
  {
    name: "Vicky Kaushal",
    email: "vicky.kaushal@gmail.com",
    gender: "Male",
    password: "123456",
    role: "User",
  },
  {
    name: "Katrina Kaif",
    email: "katrina.kaif@gmail.com",
    gender: "Female",
    password: "123456",
    role: "User",
  },
  {
    name: "Armaan Malik",
    email: "armaan.malik@gmail.com",
    gender: "Male",
    password: "123456",
    role: "User",
  },
  {
    name: "Alia Bhatt",
    email: "alia.bhatt@gmail.com",
    gender: "Female",
    password: "123456",
    role: "User",
  },
  {
    name: "Rajkummar Rao",
    email: "rajkummar.rao@gmail.com",
    gender: "Male",
    password: "123456",
    role: "User",
  },
  {
    name: "Bhumi Pednekar",
    email: "bhumi.pednekar@gmail.com",
    gender: "Female",
    password: "123456",
    role: "User",
  },
  {
    name: "Ayushmann Khurrana",
    email: "ayushmann.khurrana@gmail.com",
    gender: "Male",
    password: "123456",
    role: "User",
  },
  {
    name: "Taapsee Pannu",
    email: "taapsee.pannu@gmail.com",
    gender: "Female",
    password: "123456",
    role: "User",
  },
  {
    name: "Kartik Aaryan",
    email: "kartik.aaryan@gmail.com",
    gender: "Male",
    password: "123456",
    role: "User",
  },
  {
    name: "Kiara Advani",
    email: "kiara.advani@gmail.com",
    gender: "Female",
    password: "123456",
    role: "User",
  },
  {
    name: "Varun Dhawan",
    email: "varun.dhawan@gmail.com",
    gender: "Male",
    password: "123456",
    role: "User",
  },
  {
    name: "Jacqueline Fernandez",
    email: "jacqueline.fernandez@gmail.com",
    gender: "Female",
    password: "123456",
    role: "User",
  },
  {
    name: "Tiger Shroff",
    email: "tiger.shroff@gmail.com",
    gender: "Male",
    password: "123456",
    role: "User",
  },
  {
    name: "Disha Patani",
    email: "disha.patani@gmail.com",
    gender: "Female",
    password: "123456",
    role: "User",
  },
  {
    name: "Shahid Kapoor",
    email: "shahid.kapoor@gmail.com",
    gender: "Male",
    password: "123456",
    role: "User",
  },
  {
    name: "Mira Rajput",
    email: "mira.rajput@gmail.com",
    gender: "Female",
    password: "123456",
    role: "User",
  },
  {
    name: "Akshay Kumar",
    email: "akshay.kumar@gmail.com",
    gender: "Male",
    password: "123456",
    role: "User",
  },
  {
    name: "Twinkle Khanna",
    email: "twinkle.khanna@gmail.com",
    gender: "Female",
    password: "123456",
    role: "User",
  },
  {
    name: "Hrithik Roshan",
    email: "hrithik.roshan@gmail.com",
    gender: "Male",
    password: "123456",
    role: "User",
  },
  {
    name: "Saba Azad",
    email: "saba.azad@gmail.com",
    gender: "Female",
    password: "123456",
    role: "User",
  },
  {
    name: "Ranbir Kapoor",
    email: "ranbir.kapoor@gmail.com",
    gender: "Male",
    password: "123456",
    role: "User",
  },
  {
    name: "Neetu Kapoor",
    email: "neetu.kapoor@gmail.com",
    gender: "Female",
    password: "123456",
    role: "User",
  },
  {
    name: "Aditya Banerjee",
    email: "aditya.banerjee@gmail.com",
    gender: "Male",
    password: "123456",
    role: "User",
  },
  {
    name: "Anjali Chaturvedi",
    email: "anjali.chaturvedi@gmail.com",
    gender: "Female",
    password: "123456",
    role: "User",
  },
  {
    name: "Vedant Deshpande",
    email: "vedant.deshpande@gmail.com",
    gender: "Male",
    password: "123456",
    role: "User",
  },
  {
    name: "Kavya Ghoshal",
    email: "kavya.ghoshal@gmail.com",
    gender: "Female",
    password: "123456",
    role: "User",
  },
  {
    name: "Rudra Iyengar",
    email: "rudra.iyengar@gmail.com",
    gender: "Male",
    password: "123456",
    role: "User",
  },
  {
    name: "Mira Jhaveri",
    email: "mira.jhaveri@gmail.com",
    gender: "Female",
    password: "123456",
    role: "User",
  },
  {
    name: "Aryan Kapoor",
    email: "aryan.kapoor@gmail.com",
    gender: "Male",
    password: "123456",
    role: "User",
  },
  {
    name: "Ishani Lal",
    email: "ishani.lal@gmail.com",
    gender: "Female",
    password: "123456",
    role: "User",
  },
  {
    name: "Dhruv Mehra",
    email: "dhruv.mehra@gmail.com",
    gender: "Male",
    password: "123456",
    role: "User",
  },
  {
    name: "Navya Nanda",
    email: "navya.nanda@gmail.com",
    gender: "Female",
    password: "123456",
    role: "User",
  },
  {
    name: "Kabir Oberoi",
    email: "kabir.oberoi@gmail.com",
    gender: "Male",
    password: "123456",
    role: "User",
  },
  {
    name: "Oorja Pandit",
    email: "oorja.pandit@gmail.com",
    gender: "Female",
    password: "123456",
    role: "User",
  },
  {
    name: "Reyansh Qureshi",
    email: "reyansh.qureshi@gmail.com",
    gender: "Male",
    password: "123456",
    role: "User",
  },
  {
    name: "Siya Rana",
    email: "siya.rana@gmail.com",
    gender: "Female",
    password: "123456",
    role: "User",
  },
  {
    name: "Virat Shetty",
    email: "virat.shetty@gmail.com",
    gender: "Male",
    password: "123456",
    role: "User",
  },
  {
    name: "Trisha Tiwari",
    email: "trisha.tiwari@gmail.com",
    gender: "Female",
    password: "123456",
    role: "User",
  },
  {
    name: "Yuvraj Upadhyay",
    email: "yuvraj.upadhyay@gmail.com",
    gender: "Male",
    password: "123456",
    role: "User",
  },
  {
    name: "Urvi Varma",
    email: "urvi.varma@gmail.com",
    gender: "Female",
    password: "123456",
    role: "User",
  },
  {
    name: "Zayan Wadhwa",
    email: "zayan.wadhwa@gmail.com",
    gender: "Male",
    password: "123456",
    role: "User",
  },
  {
    name: "Vedika Yadav",
    email: "vedika.yadav@gmail.com",
    gender: "Female",
    password: "123456",
    role: "User",
  },
  {
    name: "Advait Agarwal",
    email: "advait.agarwal@gmail.com",
    gender: "Male",
    password: "123456",
    role: "User",
  },
  {
    name: "Bhavna Biswas",
    email: "bhavna.biswas@gmail.com",
    gender: "Female",
    password: "123456",
    role: "User",
  },
  {
    name: "Chirag Chawla",
    email: "chirag.chawla@gmail.com",
    gender: "Male",
    password: "123456",
    role: "User",
  },
  {
    name: "Drishti Dutta",
    email: "drishti.dutta@gmail.com",
    gender: "Female",
    password: "123456",
    role: "User",
  },
  {
    name: "Eshaan Ezekiel",
    email: "eshaan.ezekiel@gmail.com",
    gender: "Male",
    password: "123456",
    role: "User",
  },
  {
    name: "Falguni Fadnavis",
    email: "falguni.fadnavis@gmail.com",
    gender: "Female",
    password: "123456",
    role: "User",
  },
  {
    name: "Gautam Grover",
    email: "gautam.grover@gmail.com",
    gender: "Male",
    password: "123456",
    role: "User",
  },
  {
    name: "Hiral Haldar",
    email: "hiral.haldar@gmail.com",
    gender: "Female",
    password: "123456",
    role: "User",
  },
  {
    name: "Indrajeet Iyer",
    email: "indrajeet.iyer@gmail.com",
    gender: "Male",
    password: "123456",
    role: "User",
  },
  {
    name: "Jhanvi Jaitley",
    email: "jhanvi.jaitley@gmail.com",
    gender: "Female",
    password: "123456",
    role: "User",
  },
  {
    name: "Kunal Kohli",
    email: "kunal.kohli@gmail.com",
    gender: "Male",
    password: "123456",
    role: "User",
  },
  {
    name: "Lavanya Luthra",
    email: "lavanya.luthra@gmail.com",
    gender: "Female",
    password: "123456",
    role: "User",
  },
  {
    name: "Manan Mittal",
    email: "manan.mittal@gmail.com",
    gender: "Male",
    password: "123456",
    role: "User",
  },
  {
    name: "Nandini Nair",
    email: "nandini.nair@gmail.com",
    gender: "Female",
    password: "123456",
    role: "User",
  },
  {
    name: "Omkar Oswal",
    email: "omkar.oswal@gmail.com",
    gender: "Male",
    password: "123456",
    role: "User",
  },
  {
    name: "Pari Patel",
    email: "pari.patel@gmail.com",
    gender: "Female",
    password: "123456",
    role: "User",
  },
  {
    name: "Qasim Qureshi",
    email: "qasim.qureshi@gmail.com",
    gender: "Male",
    password: "123456",
    role: "User",
  },
  {
    name: "Riya Rajput",
    email: "riya.rajput@gmail.com",
    gender: "Female",
    password: "123456",
    role: "User",
  },
  {
    name: "Sahil Saxena",
    email: "sahil.saxena@gmail.com",
    gender: "Male",
    password: "123456",
    role: "User",
  },
  {
    name: "Tara Thakur",
    email: "tara.thakur@gmail.com",
    gender: "Female",
    password: "123456",
    role: "User",
  },
  {
    name: "Ujjwal Uppal",
    email: "ujjwal.uppal@gmail.com",
    gender: "Male",
    password: "123456",
    role: "User",
  },
  {
    name: "Vanya Verma",
    email: "vanya.verma@gmail.com",
    gender: "Female",
    password: "123456",
    role: "User",
  },
  {
    name: "Wahid Wagle",
    email: "wahid.wagle@gmail.com",
    gender: "Male",
    password: "123456",
    role: "User",
  },
  {
    name: "Xena Xavier",
    email: "xena.xavier@gmail.com",
    gender: "Female",
    password: "123456",
    role: "User",
  },
  {
    name: "Yash Yogi",
    email: "yash.yogi@gmail.com",
    gender: "Male",
    password: "123456",
    role: "User",
  },
  {
    name: "Zara Zutshi",
    email: "zara.zutshi@gmail.com",
    gender: "Female",
    password: "123456",
    role: "User",
  },
  {
    name: "Aadi Anand",
    email: "aadi.anand@gmail.com",
    gender: "Male",
    password: "123456",
    role: "User",
  },
  {
    name: "Bhoomi Bajaj",
    email: "bhoomi.bajaj@gmail.com",
    gender: "Female",
    password: "123456",
    role: "User",
  },
  {
    name: "Chetan Choudhary",
    email: "chetan.choudhary@gmail.com",
    gender: "Male",
    password: "123456",
    role: "User",
  },
  {
    name: "Dia Dhar",
    email: "dia.dhar@gmail.com",
    gender: "Female",
    password: "123456",
    role: "User",
  },
  {
    name: "Eklavya Eswaran",
    email: "eklavya.eswaran@gmail.com",
    gender: "Male",
    password: "123456",
    role: "User",
  },
  {
    name: "Freya Firodia",
    email: "freya.firodia@gmail.com",
    gender: "Female",
    password: "123456",
    role: "User",
  },
  {
    name: "Giriraj Gokhale",
    email: "giriraj.gokhale@gmail.com",
    gender: "Male",
    password: "123456",
    role: "User",
  },
  {
    name: "Hansika Hiranandani",
    email: "hansika.hiranandani@gmail.com",
    gender: "Female",
    password: "123456",
    role: "User",
  },
  {
    name: "Ishwar Iyengar",
    email: "ishwar.iyengar@gmail.com",
    gender: "Male",
    password: "123456",
    role: "User",
  },
  {
    name: "Jiya Joshi",
    email: "jiya.joshi@gmail.com",
    gender: "Female",
    password: "123456",
    role: "User",
  },
  {
    name: "Kailash Kacker",
    email: "kailash.kacker@gmail.com",
    gender: "Male",
    password: "123456",
    role: "User",
  },
  {
    name: "Lakshmi Loomba",
    email: "lakshmi.loomba@gmail.com",
    gender: "Female",
    password: "123456",
    role: "User",
  },
  {
    name: "Mihir Mehendale",
    email: "mihir.mehendale@gmail.com",
    gender: "Male",
    password: "123456",
    role: "User",
  },
  {
    name: "Nitya Nene",
    email: "nitya.nene@gmail.com",
    gender: "Female",
    password: "123456",
    role: "User",
  },
  {
    name: "Om Prabhu",
    email: "om.prabhu@gmail.com",
    gender: "Male",
    password: "123456",
    role: "User",
  },
  {
    name: "Prisha Purohit",
    email: "prisha.purohit@gmail.com",
    gender: "Female",
    password: "123456",
    role: "User",
  },
  {
    name: "Quaiser Quazi",
    email: "quaiser.quazi@gmail.com",
    gender: "Male",
    password: "123456",
    role: "User",
  },
  {
    name: "Rhea Rastogi",
    email: "rhea.rastogi@gmail.com",
    gender: "Female",
    password: "123456",
    role: "User",
  },
  {
    name: "Shivam Sanyal",
    email: "shivam.sanyal@gmail.com",
    gender: "Male",
    password: "123456",
    role: "User",
  },
  {
    name: "Tiya Tandon",
    email: "tiya.tandon@gmail.com",
    gender: "Female",
    password: "123456",
    role: "User",
  },
  {
    name: "Utkarsh Udupa",
    email: "utkarsh.udupa@gmail.com",
    gender: "Male",
    password: "123456",
    role: "User",
  },
  {
    name: "Vidya Vohra",
    email: "vidya.vohra@gmail.com",
    gender: "Female",
    password: "123456",
    role: "User",
  },
  {
    name: "Walter Wali",
    email: "walter.wali@gmail.com",
    gender: "Male",
    password: "123456",
    role: "User",
  },
  {
    name: "Xerxes Xavier",
    email: "xerxes.xavier@gmail.com",
    gender: "Female",
    password: "123456",
    role: "User",
  },
  {
    name: "Yug Yajnik",
    email: "yug.yajnik@gmail.com",
    gender: "Male",
    password: "123456",
    role: "User",
  },
  {
    name: "Zoya Zaveri",
    email: "zoya.zaveri@gmail.com",
    gender: "Female",
    password: "123456",
    role: "User",
  },
  {
    name: "Aarush Ahluwalia",
    email: "aarush.ahluwalia@gmail.com",
    gender: "Male",
    password: "123456",
    role: "User",
  },
  {
    name: "Barsha Bhandari",
    email: "barsha.bhandari@gmail.com",
    gender: "Female",
    password: "123456",
    role: "User",
  },
  {
    name: "Chirag Chhabra",
    email: "chirag.chhabra@gmail.com",
    gender: "Male",
    password: "123456",
    role: "User",
  },
  {
    name: "Disha Dara",
    email: "disha.dara@gmail.com",
    gender: "Female",
    password: "123456",
    role: "User",
  },
  {
    name: "Ehsan Engineer",
    email: "ehsan.engineer@gmail.com",
    gender: "Male",
    password: "123456",
    role: "User",
  },
  {
    name: "Falguni Firoz",
    email: "falguni.firoz@gmail.com",
    gender: "Female",
    password: "123456",
    role: "User",
  },
  {
    name: "Gopal Gambhir",
    email: "gopal.gambhir@gmail.com",
    gender: "Male",
    password: "123456",
    role: "User",
  },
  {
    name: "Hetal Harsora",
    email: "hetal.harsora@gmail.com",
    gender: "Female",
    password: "123456",
    role: "User",
  },
  {
    name: "Imaad Irani",
    email: "imaad.irani@gmail.com",
    gender: "Male",
    password: "123456",
    role: "User",
  },
  {
    name: "Jivika Jalan",
    email: "jivika.jalan@gmail.com",
    gender: "Female",
    password: "123456",
    role: "User",
  },
  {
    name: "Karan Kothari",
    email: "karan.kothari@gmail.com",
    gender: "Male",
    password: "123456",
    role: "User",
  },
  {
    name: "Lavina Lulla",
    email: "lavina.lulla@gmail.com",
    gender: "Female",
    password: "123456",
    role: "User",
  },
  {
    name: "Mohan Makwana",
    email: "mohan.makwana@gmail.com",
    gender: "Male",
    password: "123456",
    role: "User",
  },
  {
    name: "Niyati Nahar",
    email: "niyati.nahar@gmail.com",
    gender: "Female",
    password: "123456",
    role: "User",
  },
  {
    name: "Omkar Oza",
    email: "omkar.oza@gmail.com",
    gender: "Male",
    password: "123456",
    role: "User",
  },
  {
    name: "Poorvi Parikh",
    email: "poorvi.parikh@gmail.com",
    gender: "Female",
    password: "123456",
    role: "User",
  },
  {
    name: "Qutubuddin Qazi",
    email: "qutubuddin.qazi@gmail.com",
    gender: "Male",
    password: "123456",
    role: "User",
  },
  {
    name: "Rashi Rathi",
    email: "rashi.rathi@gmail.com",
    gender: "Female",
    password: "123456",
    role: "User",
  },
  {
    name: "Sarthak Sibal",
    email: "sarthak.sibal@gmail.com",
    gender: "Male",
    password: "123456",
    role: "User",
  },
  {
    name: "Tanisha Talwar",
    email: "tanisha.talwar@gmail.com",
    gender: "Female",
    password: "123456",
    role: "User",
  },
  {
    name: "Uday Uthappa",
    email: "uday.uthappa@gmail.com",
    gender: "Male",
    password: "123456",
    role: "User",
  },
  {
    name: "Vasudha Venkat",
    email: "vasudha.venkat@gmail.com",
    gender: "Female",
    password: "123456",
    role: "User",
  },
  {
    name: "Wilson Wable",
    email: "wilson.wable@gmail.com",
    gender: "Male",
    password: "123456",
    role: "User",
  },
  {
    name: "Xyla Xavier",
    email: "xyla.xavier@gmail.com",
    gender: "Female",
    password: "123456",
    role: "User",
  },
  {
    name: "Yajat Yadav",
    email: "yajat.yadav@gmail.com",
    gender: "Male",
    password: "123456",
    role: "User",
  },
  {
    name: "Zara Zinta",
    email: "zara.zinta@gmail.com",
    gender: "Female",
    password: "123456",
    role: "User",
  },
];
// Immediately hash passwords and export the array
const hashedUsersPromise = Promise.all(
  users.map(async (user) => {
    const hashedPassword = await bcrypt.hash(user.password, 10);
    return {
      ...user,
      password: hashedPassword,
      role: "User",
    };
  })
);

module.exports = hashedUsersPromise;
